# Generated by Django 5.2.4 on 2025-07-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
