# Generated by Django 5.2.4 on 2025-07-17 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Title must start with "td: "', regex='^td: ')]),
        ),
    ]
