# Generated by Django 5.2.4 on 2025-08-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Who',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('todos', models.ManyToManyField(blank=True, null=True, related_name='whos', to='todo_app.todo')),
            ],
        ),
    ]
